---
title: "viz_and_eda_1"
author: "Lorraine Kwok"
date: "2019-09-25"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
# will only be using one function in ggridges
```

## create the weather data 

```{r load_data, cache = TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

## create a ggplot

```{r}
## ggplot(dataset of interest, define what's on the x and y axes) + type of plot
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

alternate way of making this plot

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

saving initial plots

```{r}
scatterplot =
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

scatterplot
```

adding color

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = .4)
## color is map feature we're interested in and name is the variable of interest
## alpha blending adds transparency to plot, 0 = transparent, 1 is not at all 
```

why do 'aes' positions matter?

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = .4) +
  geom_smooth(se = FALSE)
## geom_smooth is often used for exploratory analysis
```

vs

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE)

## resulting plot has individual points and curves color-coded by the name 
```

## create facets
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE) +
  facet_grid(~name)
## facet_grid(~name) tells R you want name in the columns
```

## create plot to analyze seasonal trend
```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .8) +
  geom_smooth(se = FALSE) 
## size = prcp -> the size of the datapoints are determined by the precipitation data
```


