---
title: "EDA"
author: "Lorraine Kwok"
data: "10/3/2019"
output: github_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
  echo = TRUE,
  fig.width = 8, 
  fig.height = 6, 
  out.width = "90%")
```

## create the weather data 

```{r load_data, cache = TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
```

## `group_by` and counting

```{r}
weather_df %>%
  group_by(name, month)
```

```{r}
weather_df %>%
  group_by(name, month) %>% 
  summarize(n_obs = n())
```

```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    n_unique = n_distinct(date))
```

```{r}
# if you're planning to use group_by, summarize and count, can just use count

weather_df %>%
  count(name, month)
```

```{r}
# don't ever do this

weather_df %>%
  pull(name) %>%
  table()
```

let's make a table 

```{r}
weather_df %>%
  count(name) %>%
  knitr::kable()
```

## (2x2 tables)

```{r}
#case_when is useful for creating two or more categories based on an existing variable 

weather_df %>%
  filter(name != "Waikiki_HA") %>%
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not cold",
      TRUE      ~ ""
    )
  ) %>%
  group_by(name, cold) %>%
  count() %>%
  pivot_wider(
    names_from = cold, 
    values_from = n
  )
```

```{r}
weather_df %>%
  filter(name != "Waikiki_HA") %>%
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not cold",
      TRUE      ~ ""
    )
  ) %>%
  janitor::tabyl(name, cold)
```

